<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Link</name>
   <tag></tag>
   <elementGuidId>d27bdcd9-65c4-46dd-96c7-51190a89753a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.p-0.ms-1.text-primary.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[27]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfd29c22-88a8-4973-b7e0-b15d08479445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff5f74a0-88e6-4474-ae0a-825bade76df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn p-0 ms-1 text-primary fw-semibold</value>
      <webElementGuid>0f76ec6a-ef9a-4d03-b51a-fea0603798dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>e125921d-7103-4722-86bc-406b4e1dad4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalTransactionMedicine&quot;)/section[@class=&quot;transaction-modal bg-light&quot;]/div[@class=&quot;p-3 d-flex flex-column gap-3&quot;]/section[1]/div[@class=&quot;row text-capitalize&quot;]/div[@class=&quot;col-6 d-flex flex-column gap-2&quot;]/div[@class=&quot;d-inline-flex&quot;]/button[@class=&quot;btn p-0 ms-1 text-primary fw-semibold&quot;]</value>
      <webElementGuid>159df446-7e75-42b2-9325-d310da2cf2a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27]</value>
      <webElementGuid>7eab023e-d80f-4036-9cac-c89ca58926fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalTransactionMedicine']/section/div[2]/section/div/div[2]/div/button</value>
      <webElementGuid>6b05b84d-072d-4fb2-8f60-af18304c0e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>4b8d1a51-2163-49b6-a30b-50f7ce297a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi Obat'])[1]/following::button[1]</value>
      <webElementGuid>2fa97f96-1811-4bf2-af8f-825dd525a9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pembelian'])[1]/preceding::button[1]</value>
      <webElementGuid>ad5ed8a3-c00b-4926-8b23-1bfb4075af04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Obat'])[1]/preceding::button[1]</value>
      <webElementGuid>4b72e6bb-6209-4a2a-9a27-12cc12baf6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>d3d2d915-d44a-4aeb-9eb6-ed5ba897bbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Link' or . = 'Link')]</value>
      <webElementGuid>87991633-3f8c-4725-af10-ddc7e15cad0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
