<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Data dokter gagal ditambahkan</name>
   <tag></tag>
   <elementGuidId>cb2b023f-734a-418f-ae5b-d732a470f229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc8e4306-67b5-4801-8d96-24d798c264fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8125d1d6-7cea-4dbc-97e9-6c560b7a9e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--light Toastify__toast--error Toastify__toast--close-on-click Toastify--animate Toastify__bounce-enter--bottom-left</value>
      <webElementGuid>50c22ae9-7c74-4810-838c-7415325e9007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data dokter gagal ditambahkan</value>
      <webElementGuid>3990a930-c40c-4314-9b1f-08d8bb1a441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)</value>
      <webElementGuid>0b7a6e9c-7190-4d00-8750-89ebf242360b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='4']</value>
      <webElementGuid>7f2b4697-056e-4dae-abfd-6096fe95a734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div</value>
      <webElementGuid>e003ca57-1327-482b-a587-e04882d37841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Dokter'])[1]/following::div[7]</value>
      <webElementGuid>475ecd84-9ffe-4d9d-91c7-fd64de72e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter'])[1]/following::div[10]</value>
      <webElementGuid>3583ae4a-353b-4e6f-a839-61b153ad75f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Foto'])[1]/preceding::div[6]</value>
      <webElementGuid>2406c0ff-ca72-49d2-b2d2-df9f2f1c2539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>00004e59-7ad4-467c-abf8-9fd4623b5ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '4' and (text() = 'Data dokter gagal ditambahkan' or . = 'Data dokter gagal ditambahkan')]</value>
      <webElementGuid>6b11c626-9990-4e15-8edd-89f54c725f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
