<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dokter berhasil diedit</name>
   <tag></tag>
   <elementGuidId>49a97cc9-b6a3-41ac-8ee0-f7cf3811a2d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73946e28-2755-4adb-b616-5fa681dbc3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8f39bb90-1ed2-4707-a4a7-a92dde6438c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toastify__toast Toastify__toast-theme--light Toastify__toast--success Toastify__toast--close-on-click</value>
      <webElementGuid>d80cc1b3-fde3-4ff1-b5ce-2a0dff59cbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokter berhasil diedit!</value>
      <webElementGuid>19568a86-211a-4c94-a648-0972ba4022a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)</value>
      <webElementGuid>80b3ceaf-41ab-4586-a450-620564a69924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='3']</value>
      <webElementGuid>fdeb0c41-21ed-4f98-ac00-c7adf368a2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div</value>
      <webElementGuid>8c4cbd1a-fba9-4c7b-9db8-932ce6d12401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Dokter'])[1]/following::div[7]</value>
      <webElementGuid>02276ffa-9a7b-4392-9d4b-ab928154eb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter'])[1]/following::div[10]</value>
      <webElementGuid>9f116a65-964a-4b37-a7d1-acba0712dac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Dokter'])[1]/preceding::div[5]</value>
      <webElementGuid>64e794d5-6665-455f-b808-348330070e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>2bc0cf3d-48aa-4f20-a41d-87e9b72bf235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '3' and (text() = 'Dokter berhasil diedit!' or . = 'Dokter berhasil diedit!')]</value>
      <webElementGuid>e7eec382-a20e-4404-b153-c1bd868cdb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
