<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pengalaman Kerja_experience</name>
   <tag></tag>
   <elementGuidId>be5972aa-30e9-454b-957a-c9ae6a58e3f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;experience&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='experience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06b16456-dc35-4006-91c3-08038a5301bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55077975-7a1c-40a1-890d-4ff3fa89a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3 col-12 col-lg input-styles </value>
      <webElementGuid>d717d6c5-5425-4e99-b3d0-80d890dce5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>experience</value>
      <webElementGuid>94f3b70f-f328-4fd6-b89c-7ad08e86cf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Pengalaman Praktik</value>
      <webElementGuid>73e18d24-fdfb-433a-a363-0ab51d8206e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;container-fluid&quot;]/div[@class=&quot;my-3 d-flex flex-column flex-lg-row align-items-center align-items-lg-start justify-content-lg-center gap-3&quot;]/div[@class=&quot;d-grid list-input pt-1&quot;]/form[@class=&quot;d-grid gap-2&quot;]/div[@class=&quot;row align-items-md-center gap-2&quot;]/input[@class=&quot;form-control p-3 col-12 col-lg input-styles&quot;]</value>
      <webElementGuid>a918f246-e0e7-4e5c-a235-e2b7724bd30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='experience']</value>
      <webElementGuid>f7400818-191e-41b9-8908-8e02f7854727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div[2]/form/div[13]/input</value>
      <webElementGuid>abf4ee15-3a5d-4cde-8931-068a67918c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>c4d60573-a4a1-45a2-b88d-602d9dbeff1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'experience' and @placeholder = 'Tahun Pengalaman Praktik']</value>
      <webElementGuid>9854e5e9-d69f-4aa7-95c6-d8604d11b42e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
