<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transaksi Konsultasi Dokter_searchDoctor</name>
   <tag></tag>
   <elementGuidId>91afa6d6-5d29-4dbb-ac0e-98aa03f1bb9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchDoctor&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchDoctor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b881cfb-ade5-4556-ba20-8ee104167156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>101affb7-201e-478d-a216-5bed699cdecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-5 ps-5 border-0 bg-white py-2</value>
      <webElementGuid>54ffd8ca-230b-4f00-bc6e-e8a1950d9292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchDoctor</value>
      <webElementGuid>63288be6-5bc0-4f25-96a9-ae2d374cf3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari ID Transaksi</value>
      <webElementGuid>da9bcebb-26b4-4c99-8e04-5c69c1437a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;mx-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border&quot;]/div[@class=&quot;d-flex flex-column flex-md-row justify-content-md-between align-items-md-center mb-4&quot;]/div[@class=&quot;position-relative mt-3 mt-md-0&quot;]/input[@class=&quot;rounded-5 ps-5 border-0 bg-white py-2&quot;]</value>
      <webElementGuid>f94a8b3c-8e38-49e2-913f-a43aa47ac660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchDoctor']</value>
      <webElementGuid>c09c32f2-243a-403b-99b2-6d38d0026a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div/div/input</value>
      <webElementGuid>dc058bf4-681b-49ff-a2f7-51103fdebc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1bdcc565-8231-4ebf-82a2-2a8b831e6963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchDoctor' and @placeholder = 'Cari ID Transaksi']</value>
      <webElementGuid>c5c5b7b8-86d9-4acd-be67-60e672c14cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
