<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tidak</name>
   <tag></tag>
   <elementGuidId>b4eb8a33-bc45-4958-9c7a-bfd909d5dcdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.text-white.fw-semibold.w-50.text-nowrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d628e2c0-8e72-4484-9534-2ab46d87dcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd06c303-7952-45e8-8987-b89276fc170b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white fw-semibold w-50 text-nowrap</value>
      <webElementGuid>02de74fd-fddb-4cb2-b693-e132cb3bb66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>c37161ba-46bc-4def-a6d9-5291be85aec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;mx-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border&quot;]/div[@class=&quot;table-responsive table-wrapper&quot;]/table[@class=&quot;table table-borderless table-striped align-middle&quot;]/tbody[1]/tr[@class=&quot;text-nowrap&quot;]/td[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;wrapper-modal&quot;]/div[@class=&quot;card border-0 d-flex flex-column rounded-4 justify-content-center custom-modal&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;d-flex flex-row justify-content-center w-100 gap-3 mt-3&quot;]/button[@class=&quot;btn btn-primary text-white fw-semibold w-50 text-nowrap&quot;]</value>
      <webElementGuid>713cb4e9-fe87-4a62-bd61-8f6435fa87e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>92589e6e-0d89-45df-8935-300d19e7f046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/table/tbody/tr/td[8]/div[2]/div/div/div/button</value>
      <webElementGuid>7ff9277f-57b3-4b45-9aea-fdb33b175059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima Pembayaran?'])[1]/following::button[1]</value>
      <webElementGuid>391d928c-959d-43ba-9dbf-09d4c752245e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima'])[1]/following::button[1]</value>
      <webElementGuid>bcf1e2a5-6103-4c2b-9a8c-f6ab01772ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::button[1]</value>
      <webElementGuid>e5cecfaa-c6ff-46ef-b2f1-a8a01c9a7f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manual transfer bri'])[1]/preceding::button[2]</value>
      <webElementGuid>eac2169d-0b20-4b7a-b420-9110792f0056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>6f8852eb-7ff8-4fb3-a341-3f9e1bb50f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>74909ff8-4757-475a-8605-d5d79fd0e065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tidak' or . = 'Tidak')]</value>
      <webElementGuid>5d141027-d2df-4ba8-b6da-242174000a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
