<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Diterima</name>
   <tag></tag>
   <elementGuidId>78ab5822-7c80-4c5e-917b-7e2d81c0e211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.fw-semibold.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/table/tbody/tr/td[8]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45c88728-2619-41ab-9781-95cb6913024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-semibold text-primary</value>
      <webElementGuid>0c6cca99-afd6-41a3-8d68-84f9b1892b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diterima</value>
      <webElementGuid>4ee11677-2c0b-4cec-b391-8ae9c24c57c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;mx-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border&quot;]/div[@class=&quot;table-responsive table-wrapper&quot;]/table[@class=&quot;table table-borderless table-striped align-middle&quot;]/tbody[1]/tr[@class=&quot;text-nowrap&quot;]/td[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;px-4 rounded-5&quot;]/p[@class=&quot;fw-semibold text-primary&quot;]</value>
      <webElementGuid>dc4ccc0d-74e3-4ed2-b125-43cacbdcd927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div/div[2]/table/tbody/tr/td[8]/div/p</value>
      <webElementGuid>33919179-211d-4143-914d-8a18185f1979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/following::p[1]</value>
      <webElementGuid>a56acbba-36d2-4a7c-b98b-a76e29a92c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 700.000'])[1]/following::p[1]</value>
      <webElementGuid>264b3fc0-fd26-468b-8aec-0fc9cced420a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manual transfer bri'])[1]/preceding::p[1]</value>
      <webElementGuid>8c90bf05-a5a3-487d-b668-cfb56cbc04ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 79.000'])[1]/preceding::p[1]</value>
      <webElementGuid>c3ec70ec-75bd-4852-b4df-6583574c8661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Diterima']/parent::*</value>
      <webElementGuid>f5f82366-43a2-4d1a-b9ba-a5fdf5de5675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/p</value>
      <webElementGuid>9fa7360f-0be1-4463-a5cb-de32141ad9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Diterima' or . = 'Diterima')]</value>
      <webElementGuid>4534097c-0e57-43d8-a276-620899b2a4b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
