<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tambah Produk_mt-2 img-fluid p-4 rounded border-primary</name>
   <tag></tag>
   <elementGuidId>996c4154-66f9-4c62-a92a-25471093a415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-2.img-fluid.p-4.rounded.border-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/main/div[2]/div[5]/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8eb611e-a532-4ea4-aecc-950369fc848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/AddPhoto-03d98a02.svg</value>
      <webElementGuid>013a396e-1974-4919-8872-81fc1a1146bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Placeholder</value>
      <webElementGuid>5d8bb3da-9414-4d44-a166-1522437ea37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 img-fluid p-4 rounded border-primary</value>
      <webElementGuid>58bf6506-f5e1-4a1e-b4c9-c9d3ece14ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-12 text-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100&quot;]/img[@class=&quot;mt-2 img-fluid p-4 rounded border-primary&quot;]</value>
      <webElementGuid>77ee9c63-390b-4071-8f56-268bd7d0f2d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>b34287fb-a964-458a-8db6-8eb6e3af041e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Placeholder']</value>
      <webElementGuid>6a132ff6-355d-4933-8554-2ba831900aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/img</value>
      <webElementGuid>7a2db2b8-18d4-4492-93c5-1835785aa167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/AddPhoto-03d98a02.svg' and @alt = 'Placeholder']</value>
      <webElementGuid>c8ff3bdd-1e61-4277-8751-7d3eee5769be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
