<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Foto</name>
   <tag></tag>
   <elementGuidId>d56c61a6-1446-4602-949f-5bafd2784b03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc85ebde-7b95-4167-be9a-987e4e345e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn fw-semibold</value>
      <webElementGuid>c5f4af0d-a6fd-435f-b651-e590359e02fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/bucketcobaja/20231207-370915-bodrex.jpg</value>
      <webElementGuid>761cd082-ab60-471a-ad72-7c9ccaf3a615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>45691eeb-f531-4837-99d6-627fb439e496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Foto</value>
      <webElementGuid>53239449-3764-4627-b009-499de749fc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;d-flex flex-column shadow rounded-2 p-2 edit-btn-wrapper&quot;]/a[@class=&quot;btn fw-semibold&quot;]</value>
      <webElementGuid>d1b742fb-7da8-44e5-b830-aafe659654f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>1ec055a8-ce6b-4857-aae4-0b7bc39454d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Foto')]</value>
      <webElementGuid>02e328ed-7775-4631-a161-38db7a58da7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Produk'])[1]/following::a[1]</value>
      <webElementGuid>1b1daa51-d0dc-4b55-b9e4-a59196b211e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[10]/following::a[1]</value>
      <webElementGuid>0680768b-c1cc-428f-bfc5-58fda48d2333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Foto'])[1]/preceding::a[1]</value>
      <webElementGuid>d191ef77-ac7f-438c-9899-39b43e101714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Foto'])[1]/preceding::a[1]</value>
      <webElementGuid>3cfd2c78-a079-4fe8-9239-3907f16e23f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Foto']/parent::*</value>
      <webElementGuid>7ec55c32-d641-40fe-ad6e-e9ca86cbd1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://storage.googleapis.com/bucketcobaja/20231207-370915-bodrex.jpg')]</value>
      <webElementGuid>053fa38b-a3fd-4110-971d-17237dd8cc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>d1e812d7-c81c-475b-9f8f-4c9a1b54e142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://storage.googleapis.com/bucketcobaja/20231207-370915-bodrex.jpg' and (text() = 'Lihat Foto' or . = 'Lihat Foto')]</value>
      <webElementGuid>7e0e5ee3-7efe-45f0-8d6b-e2b23487cbdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
