<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tidak</name>
   <tag></tag>
   <elementGuidId>2557fa4a-80e7-4c0f-b3c6-7d4e67e3fc0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.text-white.fw-semibold.w-50.text-nowrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2cc880c-ded0-4ead-8ece-a0f47cd96945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dcdf698-fc78-4466-8787-19e395aeb5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white fw-semibold w-50 text-nowrap</value>
      <webElementGuid>84e50801-0996-4b35-aa81-80bd9b42b6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>75b67686-c117-4a1d-bf5f-9ab728668bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;wrapper-modal&quot;]/div[@class=&quot;card border-0 d-flex flex-column rounded-4 justify-content-center custom-modal&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;d-flex flex-row justify-content-center w-100 gap-3 mt-3&quot;]/button[@class=&quot;btn btn-primary text-white fw-semibold w-50 text-nowrap&quot;]</value>
      <webElementGuid>6aaa786a-c89e-4b5e-b65a-6f598c50dcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>19383291-674e-4caf-8985-557599dc412c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div[4]/div/div/div/button</value>
      <webElementGuid>357fb220-442c-4c48-9daa-dd58a2d43c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Foto?'])[1]/following::button[1]</value>
      <webElementGuid>adfbcfac-3905-41a9-9f98-5f00e6ccce15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Foto'])[1]/following::button[1]</value>
      <webElementGuid>adbdf0a9-5dea-4ff7-bcc9-7fb5fba8a24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::button[1]</value>
      <webElementGuid>6af89597-0666-43d3-b467-8edfcd17e9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode'])[2]/preceding::button[2]</value>
      <webElementGuid>a8bb87d8-adf8-4627-a827-c2155735a6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>870bb4a5-d7de-4aca-a5e4-c23626349362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>bbc0f6be-ac6f-4035-b7ac-b2ebe6357f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tidak' or . = 'Tidak')]</value>
      <webElementGuid>dfbd8dd1-2005-4cba-80a5-be1d3d2db028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
