<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Informasi Produk_mt-2 mx-auto img-fluid_cbed28</name>
   <tag></tag>
   <elementGuidId>c226c09b-5acc-4a94-8e2c-5c8fcf17d75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-2.mx-auto.img-fluid.rounded.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cd48c36f-c9f7-4858-98e6-5109fcb31120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/bucketcobaja/20231207-370915-bodrex.jpg</value>
      <webElementGuid>84588309-0913-4e1d-bf6e-93e7c1a7b7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>9281e942-a73e-4849-bc70-3e477e43a24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 mx-auto img-fluid rounded false</value>
      <webElementGuid>b0c961f2-c4e7-48ee-9d76-ac2b36fd2608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;d-flex mx-auto p-0 mb-3&quot;]/img[@class=&quot;mt-2 mx-auto img-fluid rounded false&quot;]</value>
      <webElementGuid>320c2460-dd3e-41b8-a56d-4dc48c4fca82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      <webElementGuid>93d45010-adcc-405f-bbcf-e88a3ed791b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Preview']</value>
      <webElementGuid>0c2e17fc-dc94-41bf-bab4-95103e1dac4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>a571e73b-4e6a-4334-86ab-199359b92d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/bucketcobaja/20231207-370915-bodrex.jpg' and @alt = 'Preview']</value>
      <webElementGuid>2558eca4-b22d-40bc-96cb-72a6dbc7746a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
