<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Informasi Produk_mt-2 mx-auto img-fluid_cbed28_1</name>
   <tag></tag>
   <elementGuidId>dbd6172e-7f30-4f2d-9bb6-880588d70eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-2.mx-auto.img-fluid.rounded.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f5fb997-7673-44a7-ad92-a6815282208e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/bucketcobaja/20231215-550803-Free_Test_Data_1MB_JPG.jpg</value>
      <webElementGuid>28f2dbc5-54cd-4c9a-aa23-629de9f6aab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>fe8eb4d0-b196-4dcc-b1bd-93afd3faae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 mx-auto img-fluid rounded false</value>
      <webElementGuid>ee9ec321-4ce5-42a3-ac60-4c6fee939f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;position-relative&quot;]/div[@class=&quot;d-flex mx-auto p-0 mb-3&quot;]/img[@class=&quot;mt-2 mx-auto img-fluid rounded false&quot;]</value>
      <webElementGuid>3793225a-5627-4211-93e6-6e584de7a083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      <webElementGuid>a27e6cc1-3206-4127-8edc-7bd1d430f7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Preview']</value>
      <webElementGuid>2bfac20f-ab66-4b09-b3c6-a83a40fce541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>918e2330-5731-4bf1-bd1d-c6d05883d6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/bucketcobaja/20231215-550803-Free_Test_Data_1MB_JPG.jpg' and @alt = 'Preview']</value>
      <webElementGuid>92d32f45-fe3f-438d-86c0-5ccb5b44ce70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
