<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Diterima</name>
   <tag></tag>
   <elementGuidId>fad162c5-d647-4859-ae2d-f60d86847a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.text-capitalize.text-nowrap.cursor-pointer > td.d-flex.justify-content-center > div.px-4.rounded-5 > p.fw-semibold.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/section/div/div[2]/div[2]/table/tbody/tr/td[6]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>372883c6-96fa-4b21-adbd-7ad4eabadc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-semibold text-primary</value>
      <webElementGuid>cc5a9462-8656-4b95-b2cb-67ad7fa86fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diterima</value>
      <webElementGuid>6d868f22-f2fc-4bc3-8e7c-9cf9907873d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;mx-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border&quot;]/div[@class=&quot;table-responsive table-wrapper&quot;]/table[@class=&quot;table table-borderless table-striped align-middle&quot;]/tbody[1]/tr[@class=&quot;text-capitalize text-nowrap cursor-pointer&quot;]/td[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;px-4 rounded-5&quot;]/p[@class=&quot;fw-semibold text-primary&quot;]</value>
      <webElementGuid>afbf94e5-2a6d-4fb0-92a6-7493b0cf7e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div[2]/div[2]/table/tbody/tr/td[6]/div/p</value>
      <webElementGuid>389bebe1-3599-42f9-8f6b-724c08750928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 9.000'])[1]/following::p[1]</value>
      <webElementGuid>013d3d28-5668-4bd5-be49-5f0ce8c233a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manual transfer bca'])[5]/following::p[1]</value>
      <webElementGuid>2462ee0f-a8cc-4ee4-9604-ceae545e0e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manual transfer bca'])[6]/preceding::p[1]</value>
      <webElementGuid>f921d691-867d-4719-abcb-43c5a12aa2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 9.000'])[2]/preceding::p[1]</value>
      <webElementGuid>744a3b5b-a938-457e-a9ba-f7e19e013303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/p</value>
      <webElementGuid>93c5927e-8f78-4bbe-b0d4-b66982a17450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Diterima' or . = 'Diterima')]</value>
      <webElementGuid>67f39cb5-2f52-4bad-8de3-7191f0ef2769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
