<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lupa Kata Sandi</name>
   <tag></tag>
   <elementGuidId>d7499d50-a07c-4c51-82d8-9cbf1a0f431d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-center.text-white.fs-3.fw-medium.col.m-0.px-3.py-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2dfcdb63-4009-4091-8eb1-6c46cd52b445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center text-white fs-3 fw-medium col m-0 px-3 py-2</value>
      <webElementGuid>fa818892-2742-4e9b-b094-51dc454b1870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa Kata Sandi</value>
      <webElementGuid>0952851b-2788-4eed-a7ca-e035c85c5676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;container-fluid w-100&quot;]/div[@class=&quot;px-3 bg-primary row align-items-center&quot;]/p[@class=&quot;text-center text-white fs-3 fw-medium col m-0 px-3 py-2&quot;]</value>
      <webElementGuid>b101485c-8da3-42fe-8912-f809595cba06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/p</value>
      <webElementGuid>d0be9305-c45b-4cc2-80ea-b9de83c1515b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan Email disini'])[1]/preceding::p[1]</value>
      <webElementGuid>80454180-2740-4730-817d-350e6c20df4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::p[2]</value>
      <webElementGuid>c57f11e7-6625-4721-8dc4-429fc749048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lupa Kata Sandi']/parent::*</value>
      <webElementGuid>53142c43-4f24-42e8-b575-e18971eb0997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d9bfa37a-e70d-4c46-a894-d9a9e157a2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lupa Kata Sandi' or . = 'Lupa Kata Sandi')]</value>
      <webElementGuid>4707eb4f-e5e7-452e-813b-c462c3651ba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
