<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tambah Produk_mt-2 img-fluid p-4 rounde_ad7aa7</name>
   <tag></tag>
   <elementGuidId>13dc3328-b7f0-4bc3-aab5-f1ddac5fc905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-2.img-fluid.p-4.rounded.border-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1582fe65-0e42-4154-8ce2-6fd5a51cb6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/AddPhoto-03d98a02.svg</value>
      <webElementGuid>ddb7a1f7-9e07-41fd-8c5b-78bce6062a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Placeholder</value>
      <webElementGuid>b59dddb9-de46-4e1f-8fce-58d47e2342cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 img-fluid p-4 rounded border-primary</value>
      <webElementGuid>82eaad75-d655-40bd-9147-db05b095d257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-12 text-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100&quot;]/img[@class=&quot;mt-2 img-fluid p-4 rounded border-primary&quot;]</value>
      <webElementGuid>bf9b541b-f19f-4b70-aa29-a67d06d2c4df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>11e16875-9186-4e7c-b155-626ab45c9e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Placeholder']</value>
      <webElementGuid>5fdf8b1b-737a-46bc-91e8-88df745ec7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/img</value>
      <webElementGuid>174013ba-43a6-44ca-997e-2a083ff40120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/AddPhoto-03d98a02.svg' and @alt = 'Placeholder']</value>
      <webElementGuid>2a9e94b7-a354-48c8-bc1b-f08358557bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
