<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merk_merk</name>
   <tag></tag>
   <elementGuidId>c450d4e1-7e6f-4755-beb4-0198aaffae18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#merk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='merk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac30d989-6ba7-4f80-acd6-8892aa60e173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7fb040d-c144-4e57-8142-827cc419ecd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8b3e9bc-df9f-48eb-aad3-84a3b04e6b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merk</value>
      <webElementGuid>5ca1fdac-dda2-4e80-bb6e-697ccf4959c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merk</value>
      <webElementGuid>8a5bbb69-5ff6-419f-8838-49b61541d318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merk&quot;)</value>
      <webElementGuid>975d34db-47a8-4b95-a523-eb3d4b9c4e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='merk']</value>
      <webElementGuid>0ca9118b-538b-4f0f-b591-307b59b1c1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[3]/div/input</value>
      <webElementGuid>84c1b8be-16f1-44de-ad14-a187711fcce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>66271421-6299-403f-948e-1473f9d1d198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'merk' and @name = 'merk']</value>
      <webElementGuid>012247e6-1154-499d-8762-621ca4629d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
