<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stock_stock</name>
   <tag></tag>
   <elementGuidId>a8517767-5f8d-4038-93e4-eeb056f60bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40c6ffa0-a522-4f6e-99ee-7d1250a4dae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818a2d58-9517-4a98-9efb-41f46f0104ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>3ad38e36-b4ec-487f-afe0-9ecef8dc1691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stock</value>
      <webElementGuid>bd97ac98-4aa9-4372-ab3a-c77ed99dde38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stock</value>
      <webElementGuid>e380e215-53c5-4799-8e9e-294a517dc2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stock&quot;)</value>
      <webElementGuid>5cafc140-f1a2-40d6-a141-81115a54dfb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stock']</value>
      <webElementGuid>10df84e6-cd57-4aa2-93d0-68333749befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[6]/div/input</value>
      <webElementGuid>89da0e31-12f9-462f-98e5-7350fee0d258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>4c2bf935-dffc-41df-bf89-9c9d1e8fdea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'stock' and @name = 'stock']</value>
      <webElementGuid>4df25536-bc0f-472f-9314-6d5d109f9513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
