<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Automated</name>
   <tag></tag>
   <elementGuidId>f3ef8b7f-070f-45ee-93b0-2bf38e18fd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>009ddd44-5a7f-4cf9-80a3-fe7c2ae1d2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>986c6858-5dfa-4e9e-b42a-7937737acd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>00da1d86-dddd-48a8-881d-f8bd433e142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>781d7384-416f-42d9-9cd1-3dd4d32b1089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>5121cb46-87f3-4802-8252-b530725fd627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automated</value>
      <webElementGuid>100116a0-131f-40f9-9714-96ce0df5941d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details&quot;)</value>
      <webElementGuid>c86224b4-1d70-46e9-89f4-84e38122abb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='details']</value>
      <webElementGuid>a35c65e4-e7a8-4234-aabf-8e8eeee82b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[8]/div/textarea</value>
      <webElementGuid>58da844f-935b-4aae-b56d-047a0a7f8398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::textarea[1]</value>
      <webElementGuid>acdb877d-c75f-4900-b3e0-421801322f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[2]/following::textarea[1]</value>
      <webElementGuid>c7bb5e32-fee0-46f0-9164-ef0521c73623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>96b030e9-3c2e-4451-a0f8-5f39866b4d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Produk'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c408999d-1b0d-45b5-9fdf-6dddb1e424e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automated']/parent::*</value>
      <webElementGuid>ee3d43a7-fa5b-49df-a586-cce3b3e917e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7fa24f85-0108-47e7-8497-e4a4e80a6c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'details' and @name = 'details' and (text() = 'Automated' or . = 'Automated')]</value>
      <webElementGuid>c45708f7-f64e-47df-937c-301c0504d617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
