<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Au</name>
   <tag></tag>
   <elementGuidId>fc309b16-1058-42d5-8aed-d0700082f4a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d16cbb53-1945-4edd-9c53-e5344f55857a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ee2fe20-b7af-46da-8635-5bad31332bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8ffdfbf2-b15b-4ee0-b027-beb15b40eff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>06081821-2154-40c3-b86e-b991926a4eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>a3168161-f3f5-4016-b013-9928c35b6c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Au</value>
      <webElementGuid>8695af37-e376-4397-a8c6-5eb912e91e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details&quot;)</value>
      <webElementGuid>2d4e74ba-2bdb-42e3-8117-54af9c94bad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='details']</value>
      <webElementGuid>94a27bac-7938-48d5-bf5e-e87d758c587d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[8]/div/textarea</value>
      <webElementGuid>e0e1b4aa-1d67-4001-af47-658db31b75e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::textarea[1]</value>
      <webElementGuid>151df256-068f-49ee-abcc-3ea001c8f774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[2]/following::textarea[1]</value>
      <webElementGuid>a1e38d0c-6891-45a6-bc2d-5ee7024ea707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a1f5036f-ef1c-4e01-b31f-f50878417c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Produk'])[1]/preceding::textarea[1]</value>
      <webElementGuid>55b2d14c-8b95-49ba-8373-abaf0c5b8230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Au']/parent::*</value>
      <webElementGuid>71d8a14b-e17d-4ca9-8ef8-b8f8c33add39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>76ad5fc8-58c8-4f21-8b1b-ecfd8672c774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'details' and @name = 'details' and (text() = 'Au' or . = 'Au')]</value>
      <webElementGuid>29872fa5-1a4c-481b-8da5-4f27421874bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
