<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mulai Konsultasi</name>
   <tag></tag>
   <elementGuidId>4f3c4dd1-86c1-4db9-9880-ea2afa95c561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.rounded-5.text-white.fs-4.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[3]/div[2]/div/div/div/div[2]/table/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2167ffaa-a077-46b8-b7fe-955f528f1d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary rounded-5 text-white fs-4 fw-semibold</value>
      <webElementGuid>03139ed8-efe2-4cf6-b7ca-16f8194df561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/chat/user?status=all&amp;room=78</value>
      <webElementGuid>b6d0701b-bac0-4643-ab67-8f5b34f7a542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mulai Konsultasi</value>
      <webElementGuid>71171491-7555-445c-86e7-ad3965cb1e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;p-2 w-100 home-container bg-transparent&quot;]/div[@class=&quot;row mt-3 home-container mx-2 me-lg-4&quot;]/div[@class=&quot;col-12 col-lg-7 mb-3 mb-lg-0 px-0 px-md-3 d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 shadow-base bg-white&quot;]/div[@class=&quot;table-responsive table-wrapper&quot;]/table[@class=&quot;table table-borderless table-striped align-middle&quot;]/tbody[1]/tr[@class=&quot;text-nowrap&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary rounded-5 text-white fs-4 fw-semibold&quot;]</value>
      <webElementGuid>9760f648-8fa7-435e-9974-2dd936096b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div[2]/div/div/div/div[2]/table/tbody/tr/td[5]/a</value>
      <webElementGuid>76d416c2-2318-4659-af7f-5930826cf390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mulai Konsultasi')]</value>
      <webElementGuid>06aa5303-771d-4119-a0fc-2bf15be9deb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fadlilah Azizah'])[3]/following::a[1]</value>
      <webElementGuid>c0d197e4-0aeb-47d5-b0c9-1691b668d1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[1]/following::a[1]</value>
      <webElementGuid>c876c344-ad38-403b-a159-da79aa0124de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/preceding::a[1]</value>
      <webElementGuid>4e18c039-26fc-4e99-9e3a-bbcebca09b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fadlilah Azizah'])[4]/preceding::a[2]</value>
      <webElementGuid>bea0073b-07e8-4ff9-a642-10e40c800648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mulai Konsultasi']/parent::*</value>
      <webElementGuid>2a9cf24c-a1bf-4bc2-81b2-bdd78f277529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/chat/user?status=all&amp;room=78')]</value>
      <webElementGuid>5f4e28cc-d4b3-4f5e-b31c-c56a201b65fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>1f9fb9d5-e54e-4772-82ac-9ee1fe35b075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/chat/user?status=all&amp;room=78' and (text() = 'Mulai Konsultasi' or . = 'Mulai Konsultasi')]</value>
      <webElementGuid>2c70bb75-1438-454b-9883-e7a9d14c91b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
