<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah Artikel</name>
   <tag></tag>
   <elementGuidId>f8ae27c2-1cfc-44ec-a723-ee52ccda781b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/section/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.text-white.align-items-center.gap-2.d-flex.flex-row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3cc462f-b950-4aad-bf24-26731ad5a8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white align-items-center gap-2 d-flex flex-row</value>
      <webElementGuid>1ad60ed8-14ff-448f-a8d6-d430ada669f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/articles/create</value>
      <webElementGuid>7878e690-f25a-46e8-9bcf-eecbd5492b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Artikel</value>
      <webElementGuid>b8003e3c-ac78-47b5-82a9-586cb14a1b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;d-flex flex-row justify-content-between mx-4 my-4&quot;]/a[@class=&quot;btn btn-primary text-white align-items-center gap-2 d-flex flex-row&quot;]</value>
      <webElementGuid>2d50ecb7-bda7-403b-9811-cf414cacd8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/a</value>
      <webElementGuid>4fc48520-aab3-44c8-9951-27d3c7867925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/following::a[1]</value>
      <webElementGuid>536054f1-f773-466e-b667-643594104b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Artikel'])[2]/following::a[1]</value>
      <webElementGuid>c471c5a5-ffd2-4539-a0e9-e6d1e7ca55e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengenal Stunting dan Gizi Buruk'])[1]/preceding::a[1]</value>
      <webElementGuid>a0ef3360-3acd-4a6b-8fbc-95b82e614f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pentingnya Menjaga Kesehatan Mental pada Remaja'])[1]/preceding::a[2]</value>
      <webElementGuid>43a545dd-02cc-4cf5-bd73-7d82a62ac029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/articles/create')]</value>
      <webElementGuid>8fef7f03-26cd-4685-a11d-4b15e13d9f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>88f9621e-4f69-492f-842b-e57c5b47496e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/articles/create' and (text() = 'Tambah Artikel' or . = 'Tambah Artikel')]</value>
      <webElementGuid>1a25838e-3eb2-4b36-bd9f-81e027f925e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
