<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Portal Dokter</name>
   <tag></tag>
   <elementGuidId>66532a54-6aca-4b8c-a2ab-4d92fa6b2c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/form/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.fw-bold.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>15e9c3ed-a59d-4f73-956c-b47449f204c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-primary</value>
      <webElementGuid>81b1ea38-fec7-4247-9b09-6427c40f384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portal Dokter</value>
      <webElementGuid>1ddbbc8b-a14a-4fbe-adde-887e5502f613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-vh-100 px-5&quot;]/div[@class=&quot;d-flex min-vh-100 flex-column flex-md-row justify-content-evenly align-items-center&quot;]/div[2]/form[@class=&quot;mt-3&quot;]/div[@class=&quot;mb-3&quot;]/h3[@class=&quot;fw-bold text-primary&quot;]</value>
      <webElementGuid>30fc8c60-3321-413c-88ad-3de9c3934122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/h3</value>
      <webElementGuid>6031e4ca-efc9-401e-8917-41588e3e7e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::h3[1]</value>
      <webElementGuid>dbfbbea3-8956-4186-a15c-74f22c7dc862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::h3[1]</value>
      <webElementGuid>37d432df-7f3c-4d8b-bdb0-886ef8288890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Portal Dokter']/parent::*</value>
      <webElementGuid>3e25181e-922b-46f0-a552-bbebcec5dbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>45148600-ea0a-43bf-af71-cd77d5d66daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Portal Dokter' or . = 'Portal Dokter')]</value>
      <webElementGuid>105b5aec-40ab-4af8-b93e-4dd76e932bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
