<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Dashboard</name>
   <tag></tag>
   <elementGuidId>a00a2729-cef7-4ec7-96a3-bbc6ae2ed9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/header/nav/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.fw-semibold.m-0.text-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>03a9099c-c704-4096-a499-f473ed31839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-semibold m-0 text-secondary</value>
      <webElementGuid>323eada2-6dd7-494f-ade0-fb7a9599288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>78a306bb-cd47-4bd0-bed0-7deb4578d240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/header[@class=&quot;navbar p-0&quot;]/nav[@class=&quot;navbar-content&quot;]/div[@class=&quot;d-flex flex-row align-items-center gap-2&quot;]/h5[@class=&quot;fw-semibold m-0 text-secondary&quot;]</value>
      <webElementGuid>05af0d24-9410-4e79-94fa-b84fd8e2c654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/header/nav/div/h5</value>
      <webElementGuid>6bb25e07-d08b-40c9-839d-194ada9e4090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::h5[1]</value>
      <webElementGuid>80688f97-8518-4779-8d00-ea2c2fbfefab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelola Artikel'])[1]/following::h5[1]</value>
      <webElementGuid>ce31f9b0-e73b-4db6-b32d-5cb84a8484a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/preceding::h5[1]</value>
      <webElementGuid>b0d7b6a9-7557-4cee-a9e4-8789b2779f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pasien'])[1]/preceding::h5[1]</value>
      <webElementGuid>93420b28-3de8-44d2-8ee4-d40f6f344700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/h5</value>
      <webElementGuid>f389bb70-2eea-4911-9405-40d1c36edd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>b743c0b7-2301-47a1-8140-9b6b8371e83e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
