<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Carebot_send-icon position-absolute</name>
   <tag></tag>
   <elementGuidId>db5375ea-ed0c-4832-980e-daba568e24c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/header/nav/div[2]/div[2]/div/form/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.send-icon.position-absolute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c7362151-597d-4f93-ae54-51f1aef0d712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml,%3csvg%20width='31'%20height='31'%20viewBox='0%200%2030%2031'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cmask%20id='mask0_999_2163'%20style='mask-type:alpha'%20maskUnits='userSpaceOnUse'%20x='0'%20y='0'%20width='30'%20height='31'%3e%3crect%20y='0.5'%20width='30'%20height='30'%20fill='%23D9D9D9'/%3e%3c/mask%3e%3cg%20mask='url(%23mask0_999_2163)'%3e%3cpath%20d='M3.75%2025.5V5.5L27.5%2015.5L3.75%2025.5ZM6.25%2021.75L21.0625%2015.5L6.25%209.25V13.625L13.75%2015.5L6.25%2017.375V21.75Z'%20fill='%234E4E4E'/%3e%3c/g%3e%3c/svg%3e</value>
      <webElementGuid>3a1dbbdc-e330-4383-8f88-863de2d58561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>f2ce34ad-ab7f-4872-8e38-cad113aafa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>send-icon position-absolute</value>
      <webElementGuid>e8ce15b9-730c-4043-b42f-e11cff7841c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/header[@class=&quot;navbar p-0&quot;]/nav[@class=&quot;navbar-content&quot;]/div[@class=&quot;d-flex flex-row-reverse position-relative  flex-md-column pe-md-0&quot;]/div[@class=&quot;popup-background&quot;]/div[@class=&quot;chatbot-container pt-5 bg-white&quot;]/form[@class=&quot;user-input&quot;]/div[@class=&quot;position-relative w-100&quot;]/button[@class=&quot;send-button&quot;]/img[@class=&quot;send-icon position-absolute&quot;]</value>
      <webElementGuid>a38a58d1-2f12-45ea-a21b-0db6ed902516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/header/nav/div[2]/div[2]/div/form/div/button/img</value>
      <webElementGuid>aafd0ec3-196e-452d-bc4d-49e65e258aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Send']</value>
      <webElementGuid>7801c40f-2d26-42cc-957a-0335b5aa7947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button/img</value>
      <webElementGuid>a6bab460-4572-4e73-a0fb-e033dcf6bf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = concat(&quot;data:image/svg+xml,%3csvg%20width=&quot; , &quot;'&quot; , &quot;31&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;31&quot; , &quot;'&quot; , &quot;%20viewBox=&quot; , &quot;'&quot; , &quot;0%200%2030%2031&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;none&quot; , &quot;'&quot; , &quot;%20xmlns=&quot; , &quot;'&quot; , &quot;http://www.w3.org/2000/svg&quot; , &quot;'&quot; , &quot;%3e%3cmask%20id=&quot; , &quot;'&quot; , &quot;mask0_999_2163&quot; , &quot;'&quot; , &quot;%20style=&quot; , &quot;'&quot; , &quot;mask-type:alpha&quot; , &quot;'&quot; , &quot;%20maskUnits=&quot; , &quot;'&quot; , &quot;userSpaceOnUse&quot; , &quot;'&quot; , &quot;%20x=&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;%20y=&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;%20width=&quot; , &quot;'&quot; , &quot;30&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;31&quot; , &quot;'&quot; , &quot;%3e%3crect%20y=&quot; , &quot;'&quot; , &quot;0.5&quot; , &quot;'&quot; , &quot;%20width=&quot; , &quot;'&quot; , &quot;30&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;30&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;%23D9D9D9&quot; , &quot;'&quot; , &quot;/%3e%3c/mask%3e%3cg%20mask=&quot; , &quot;'&quot; , &quot;url(%23mask0_999_2163)&quot; , &quot;'&quot; , &quot;%3e%3cpath%20d=&quot; , &quot;'&quot; , &quot;M3.75%2025.5V5.5L27.5%2015.5L3.75%2025.5ZM6.25%2021.75L21.0625%2015.5L6.25%209.25V13.625L13.75%2015.5L6.25%2017.375V21.75Z&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;%234E4E4E&quot; , &quot;'&quot; , &quot;/%3e%3c/g%3e%3c/svg%3e&quot;) and @alt = 'Send']</value>
      <webElementGuid>1b19a25a-b4a0-4376-8336-0ca007c6c125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
