<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>5f7451ef-0f18-4816-8ec2-cb5c332660b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='medicineCard']/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;add&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65fbdcf4-4647-4d10-8100-693002cc7856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml,%3csvg%20width='24'%20height='24'%20viewBox='0%200%2024%2024'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M19%2013H13V19H11V13H5V11H11V5H13V11H19V13Z'%20fill='%23FBFBFB'/%3e%3c/svg%3e</value>
      <webElementGuid>0b3d63ed-9422-4957-8eaf-69273e80dff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>cfd3696e-8079-4710-84d2-14d38967698e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescriptionModal&quot;)/div[@class=&quot;row px-2 overflow-y-scroll&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-2 mb-4&quot;]/div[@id=&quot;medicineCard&quot;]/div[@class=&quot;d-flex flex-column gap-1&quot;]/div[@class=&quot;d-flex flex-row justify-content-between gap-2 align-items-center&quot;]/button[@class=&quot;btn btn-primary btn-sm d-flex justify-content-center rounded-5&quot;]/img[1]</value>
      <webElementGuid>e35a1818-bd80-4e9e-b98c-5493a116f4cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='medicineCard']/div/div/button/img</value>
      <webElementGuid>3b543699-fa6e-4224-8f4e-1e0f298d86b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='add']</value>
      <webElementGuid>e59c99a2-2d18-440f-b2ab-56c540d5320f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button/img</value>
      <webElementGuid>15a75720-25d8-48f2-a45a-8906c0c0c780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = concat(&quot;data:image/svg+xml,%3csvg%20width=&quot; , &quot;'&quot; , &quot;24&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;24&quot; , &quot;'&quot; , &quot;%20viewBox=&quot; , &quot;'&quot; , &quot;0%200%2024%2024&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;none&quot; , &quot;'&quot; , &quot;%20xmlns=&quot; , &quot;'&quot; , &quot;http://www.w3.org/2000/svg&quot; , &quot;'&quot; , &quot;%3e%3cpath%20d=&quot; , &quot;'&quot; , &quot;M19%2013H13V19H11V13H5V11H11V5H13V11H19V13Z&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;%23FBFBFB&quot; , &quot;'&quot; , &quot;/%3e%3c/svg%3e&quot;) and @alt = 'add']</value>
      <webElementGuid>7f76cd2d-a1f5-4398-a632-1c254bcd5a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
