<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carebot_Input-bot</name>
   <tag></tag>
   <elementGuidId>6bb740fa-cb6d-45bc-9a6d-c42af530aaa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Input-bot']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Input-bot&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98ed15a1-f92b-4763-ac6d-7b30282e7d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input-bot</value>
      <webElementGuid>a63b5c23-19f6-401f-b42c-bbbd2d5fb727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eae978ab-625b-4276-a5b9-3a91ab8d16f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kirim Pertanyaan</value>
      <webElementGuid>4418322b-9f73-43c2-afb2-b06503558b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-field rounded-5 border-0 w-100 pe-5 bg-neutral-200</value>
      <webElementGuid>3f0b8ecc-9b2c-4fbb-90e7-6d7b92f186b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/header[@class=&quot;navbar p-0&quot;]/nav[@class=&quot;navbar-content&quot;]/div[@class=&quot;d-flex flex-row-reverse position-relative  flex-md-column pe-md-0&quot;]/div[@class=&quot;popup-background&quot;]/div[@class=&quot;chatbot-container pt-5 bg-white&quot;]/form[@class=&quot;user-input&quot;]/div[@class=&quot;position-relative w-100&quot;]/input[@class=&quot;form-control input-field rounded-5 border-0 w-100 pe-5 bg-neutral-200&quot;]</value>
      <webElementGuid>6db9399b-133d-43ec-ad50-eaeb330ff030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Input-bot']</value>
      <webElementGuid>a593ebb5-6374-45f0-85e4-2a97dbeab2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/header/nav/div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>97e543b3-5a9b-4c0c-a17f-256636b562ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>cb641b1f-5d61-4def-9435-b545094c080e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Input-bot' and @type = 'text' and @placeholder = 'Kirim Pertanyaan']</value>
      <webElementGuid>e269a5e8-29e3-4387-b9a3-790d63ead6b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
