<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar Pasien_searchPatient</name>
   <tag></tag>
   <elementGuidId>eb6cf111-3e65-48f5-9c40-125a36b27c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchPatient&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchPatient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a7eb4c0-230e-42b4-b7c0-fd279b94b0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f2b76e7-6c85-4751-a461-09e84d986290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchPatient</value>
      <webElementGuid>16537a5c-45fd-4323-8702-c28122cdbc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Nama, Status,  ID Transaksi</value>
      <webElementGuid>aa218eff-9224-4e5d-b1ce-5fab5b47059f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-5 ps-5 border-0 bg-white py-2</value>
      <webElementGuid>00fd976f-7262-4679-bf3e-441ea16eec40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;p-2 w-100 patient-container&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border-top&quot;]/div[@class=&quot;d-flex flex-column flex-md-row justify-content-md-between align-items-md-center mb-4&quot;]/div[@class=&quot;position-relative mt-3 mt-md-0&quot;]/input[@class=&quot;form-control rounded-5 ps-5 border-0 bg-white py-2&quot;]</value>
      <webElementGuid>15b91f6e-dd3f-4929-946d-db9c8e7ffd8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchPatient']</value>
      <webElementGuid>0c5a8bb9-d511-491f-8560-79bd2ffbfc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div[2]/div/div/input</value>
      <webElementGuid>ad333967-921e-4f1b-a21f-5d6dc5c2f60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/input</value>
      <webElementGuid>6bd724f5-2c70-4564-8d02-91492ebda5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchPatient' and @placeholder = 'Cari Nama, Status,  ID Transaksi']</value>
      <webElementGuid>5816657c-d0ba-4501-8ff7-7e58c8c5a578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
