<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Gambar</name>
   <tag></tag>
   <elementGuidId>bfb5e6a3-afc0-4441-ae89-f04d63153981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[3]/section[2]/section/div[3]/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.text-black.bg-white.w-100.h-100.pt-2.cursor-pointer.text-start.fw-semibold.bg-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a40e348f-a0f5-4d65-aedc-e50aefb34cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fileWhite</value>
      <webElementGuid>91657766-00e5-4113-9ed2-a1ee35e6c5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black bg-white w-100 h-100 pt-2 cursor-pointer text-start fw-semibold bg-light</value>
      <webElementGuid>acebad7a-c696-4074-8f68-81952805d704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gambar</value>
      <webElementGuid>ff8a51b4-d60c-4f9e-9979-9eb1ad706114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;d-flex flex-row w-100&quot;]/section[@class=&quot;chat-body__wrapper&quot;]/section[@class=&quot;chat-body-wrapper position-relative&quot;]/div[@class=&quot;sticky-bottom z-1&quot;]/div[@class=&quot;bg-white p-2 d-flex flex-column gap-1 shadow rounded-2 position-absolute&quot;]/div[@class=&quot;text-center d-flex flex-row gap-2 align-items-center cursor-pointer&quot;]/label[@class=&quot;text-black bg-white w-100 h-100 pt-2 cursor-pointer text-start fw-semibold bg-light&quot;]</value>
      <webElementGuid>471e7a24-97bc-4c62-b12f-e17e0147a7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/section[2]/section/div[3]/div/div/label</value>
      <webElementGuid>58c0c066-d3c3-4096-9d76-98e2843f6b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/following::label[1]</value>
      <webElementGuid>14e6c9c8-e9ed-49fd-aeb8-03864ff56f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support the audio element.'])[1]/following::label[1]</value>
      <webElementGuid>7302f174-8d6a-40af-a4b7-71ccc581ff90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gambar']/parent::*</value>
      <webElementGuid>392736a0-8fd4-4439-a2b9-df96cd2c04e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>581bbe53-6b59-4690-a6ba-a359f4c7869a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Gambar' or . = 'Gambar')]</value>
      <webElementGuid>5e029d24-7b9b-4795-892b-8156c2eed959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
