<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_v</name>
   <tag></tag>
   <elementGuidId>25592a02-3ef5-47d5-a63d-1b89c0a39e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f8d6457f-92c3-4ead-b5c1-8bf531fdf464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ced2d52-eb8f-441c-aebd-6efeb883822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03cd08ac-3d23-42c7-8631-38656cbbdc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4f0a347-8d65-4000-9399-71966f8fa046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0f61b25-11a4-41d9-bc84-92934d167812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>095afc7c-2c27-4025-b05b-3287bb671373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-md-editor-text-input </value>
      <webElementGuid>675df323-5813-4b54-b30e-e73dea9822b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>66057275-ba37-4fa4-aef6-d318107e4f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;px-4 d-flex flex-column gap-4 mt-3&quot;]/div[@class=&quot;mb-5&quot;]/div[1]/div[@class=&quot;bg-light wmde-markdown-var w-md-editor w-md-editor-show-live&quot;]/div[@class=&quot;w-md-editor-content&quot;]/div[@class=&quot;w-md-editor-area w-md-editor-input&quot;]/div[@class=&quot;w-md-editor-text&quot;]/textarea[@class=&quot;w-md-editor-text-input&quot;]</value>
      <webElementGuid>9f719652-caac-4c43-8c88-a064e9b76252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>30d9a23e-f11c-4a40-8e0e-2cc1c376e590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v'])[1]/following::textarea[1]</value>
      <webElementGuid>c3953cae-370b-4cd3-9534-d371607ee28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title 6'])[1]/following::textarea[1]</value>
      <webElementGuid>e9eb84db-596f-46f0-81a1-164470ff3c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e9d89cde-e47c-40ee-bdf1-5a611921e767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'v' or . = 'v')]</value>
      <webElementGuid>d8db2c5c-329c-479a-9723-dbaf6d02c358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
