<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Title 6_w-md-editor-text-input</name>
   <tag></tag>
   <elementGuidId>372213ce-8387-4a56-8d4c-2f1b003736d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>08d0fc47-583c-40e9-96ea-8b2a6ce0ee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd5bc0e9-6f4a-4caf-8e47-0446750b45ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c57338fd-91da-40d3-976b-bc1e4e43e237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a78302ed-efce-427c-8746-288db3d07705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa2e6f8b-b243-42b7-886f-e2a786556c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8e836b65-4a62-4a1a-8a12-1b7a44f8f39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-md-editor-text-input </value>
      <webElementGuid>27619849-bcf7-4801-80b1-08dcc4041ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;px-4 d-flex flex-column gap-4 mt-3&quot;]/div[@class=&quot;mb-5&quot;]/div[1]/div[@class=&quot;bg-light wmde-markdown-var w-md-editor w-md-editor-show-live&quot;]/div[@class=&quot;w-md-editor-content&quot;]/div[@class=&quot;w-md-editor-area w-md-editor-input&quot;]/div[@class=&quot;w-md-editor-text&quot;]/textarea[@class=&quot;w-md-editor-text-input&quot;]</value>
      <webElementGuid>0c9f6af8-ff28-4b67-a6ee-21776bdd12eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>b53621f2-2202-4ec5-be8f-8382f424d0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>905f9d15-d619-42eb-8619-9ed847fa83ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
