<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_httpshealthify-doctor.vercel.app</name>
   <tag></tag>
   <elementGuidId>57024d21-1b1f-41c9-9902-e137060bc539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>53538fad-f199-4c54-b2da-459d023145e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4cede08d-f90f-4d15-a242-42ed1cebb150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b3199bf-32c1-4743-a933-8f34c6a39e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a4ef1a22-09da-4680-a017-be09920500da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9e117e2-c2ee-4280-b9b5-7f8c8a72bd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5993f7c1-5fa5-494c-b68d-23a845785d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-md-editor-text-input </value>
      <webElementGuid>69c61af0-f998-4ef7-8f14-cb5b4419daeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://healthify-doctor.vercel.app/</value>
      <webElementGuid>f39102a1-bea7-41b8-8439-358d5e7ccd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row main-layout&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;px-4 d-flex flex-column gap-4 mt-3&quot;]/div[@class=&quot;mb-5&quot;]/div[1]/div[@class=&quot;bg-light wmde-markdown-var w-md-editor w-md-editor-show-live&quot;]/div[@class=&quot;w-md-editor-content&quot;]/div[@class=&quot;w-md-editor-area w-md-editor-input&quot;]/div[@class=&quot;w-md-editor-text&quot;]/textarea[@class=&quot;w-md-editor-text-input&quot;]</value>
      <webElementGuid>17355b58-93b8-4481-8ab5-675d23cb3672</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div[3]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>784fba06-25bd-4ec8-a548-98f63999d2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://healthify-doctor.vercel.app/'])[1]/following::textarea[1]</value>
      <webElementGuid>78c0e589-6975-4c79-b7bd-3a3b5c029314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title 6'])[1]/following::textarea[1]</value>
      <webElementGuid>2f2ea912-894b-4148-9438-549d2422ab5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://healthify-doctor.vercel.app/'])[3]/preceding::textarea[1]</value>
      <webElementGuid>e0320d42-3df0-467f-9dbf-827d01243a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>22406ba3-1cee-4f5c-a2bd-48b72d96c4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'https://healthify-doctor.vercel.app/' or . = 'https://healthify-doctor.vercel.app/')]</value>
      <webElementGuid>2964d4ee-e9c7-40d0-9561-b9a94b0865f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
