<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apa itu Healthify</name>
   <tag></tag>
   <elementGuidId>5a08a991-fd77-4ce1-a5bb-da229502c2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.accordion-button.bg-white.rounded-4.text-primary.fw-bold.shadow-none.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02c97654-c636-4ee7-ae34-c3bebbb7a71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title</value>
      <webElementGuid>f7c518c0-91f3-46e0-a18a-9d14a067b984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05de6453-80e0-458a-a6e8-469721e28e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>827b6dd5-1563-48be-abe7-67c54fb2eede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#acordionhealthifyIntro</value>
      <webElementGuid>dbc27ad2-c927-41ab-aa51-72ccbf65c5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>658a1879-4036-4a62-bb62-342227460e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acordionhealthifyIntro</value>
      <webElementGuid>4f88f4e7-26c8-47ad-b8dd-2552e287967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apa itu Healthify ?</value>
      <webElementGuid>f29cd083-7c2d-4952-92eb-e1615562a3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPanelsStayOpenExample&quot;)/div[@class=&quot;accordion-item border-0 rounded-4 shadow-sm&quot;]/h2[@class=&quot;accordion-header rounded-4&quot;]/button[@class=&quot;accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title&quot;]</value>
      <webElementGuid>2fc04b85-936a-42e0-a34d-24717c87ef0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>84d42569-e912-4740-b331-f873414dd8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionPanelsStayOpenExample']/div/h2/button</value>
      <webElementGuid>f0cfbe1d-9129-44da-8c51-8868f352377c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Asked Question'])[1]/following::button[1]</value>
      <webElementGuid>377780e1-cb21-49a5-95d9-40f930a6171e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mawar Eva'])[1]/following::button[1]</value>
      <webElementGuid>911508f5-c51c-4b37-80c8-cc8b2c1d6519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara saya mendaftar di Healthify ?'])[1]/preceding::button[1]</value>
      <webElementGuid>92559803-2a34-43a2-9d3f-f03383ebff18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara berkonsultasi dengan dokter ?'])[1]/preceding::button[2]</value>
      <webElementGuid>80e464c9-7776-4ad7-b1cc-74b18b717bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apa itu Healthify ?']/parent::*</value>
      <webElementGuid>0bc748f8-7208-48bd-bf93-0e84b8fc745f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/button</value>
      <webElementGuid>57717c96-7939-40d3-8fea-a0210d7a84b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apa itu Healthify ?' or . = 'Apa itu Healthify ?')]</value>
      <webElementGuid>2b59619e-dbfa-4891-889e-72ca2991a591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
