<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bagaimana cara berkonsultasi dengan dokter</name>
   <tag></tag>
   <elementGuidId>2e29711c-686d-4bb9-a6f2-881f4a101285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>089138d5-2014-4cab-8cb0-0965d2d6161c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title</value>
      <webElementGuid>67f54d3a-70d3-4ee8-a8f6-cc6e32f58b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75aa41a8-e6ef-4655-9ad7-b3a454bac18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>94d56150-b81a-42e4-b7a4-56ab4cdca6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#acordionhealthifyConsult</value>
      <webElementGuid>9dede204-05a1-449d-b561-725a7fb66330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08720b84-a92e-4404-82a4-b5b70e0583f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acordionhealthifyConsult</value>
      <webElementGuid>2c28e7ac-da7a-498a-a5ca-912fa5fca516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagaimana cara berkonsultasi dengan dokter ?</value>
      <webElementGuid>897dd92b-bd15-485e-a4ff-d2b62dc9d740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPanelsStayOpenExample&quot;)/div[@class=&quot;accordion-item border-0 rounded-4 shadow-sm&quot;]/h2[@class=&quot;accordion-header rounded-4&quot;]/button[@class=&quot;accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title&quot;]</value>
      <webElementGuid>dc980061-a1e7-4c88-9061-6a683235a1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>865b3f66-3eee-4810-99a7-869812dc0e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionPanelsStayOpenExample']/div[3]/h2/button</value>
      <webElementGuid>120a6b31-3356-4d52-a69e-979be7dfc8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara saya mendaftar di Healthify ?'])[1]/following::button[1]</value>
      <webElementGuid>3e9de660-d68e-4b9c-b152-798419bf5d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa itu Healthify ?'])[1]/following::button[2]</value>
      <webElementGuid>08bbc7f3-34d3-450c-b72a-1d141e7afdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah konsultasi dokter online aman?'])[1]/preceding::button[1]</value>
      <webElementGuid>03882e13-e783-470e-80c0-b125746586a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara memesan obat di apotek online?'])[1]/preceding::button[2]</value>
      <webElementGuid>b05fd57a-b05c-419b-9b44-1d976a50cfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagaimana cara berkonsultasi dengan dokter ?']/parent::*</value>
      <webElementGuid>455162e2-14f0-405e-bec8-1d16b922b656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h2/button</value>
      <webElementGuid>bf317b3b-5ad0-4439-b244-ac21b86780cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Bagaimana cara berkonsultasi dengan dokter ?' or . = 'Bagaimana cara berkonsultasi dengan dokter ?')]</value>
      <webElementGuid>cd44cb2a-66d9-4d6d-8bc0-ff8437da0100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
