<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bagaimana cara memesan obat di apote_ca8a27</name>
   <tag></tag>
   <elementGuidId>0a38b9fb-c309-48fd-9bb3-23e55c53259e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9710020-f979-474b-a3e9-32412e4215e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title</value>
      <webElementGuid>85a5442a-74b0-4826-b02c-0945272d7fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68268399-0801-4512-a193-382363a149fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>4842490f-102c-48ac-9509-59387bf7a903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#acordionhealthifyDrug</value>
      <webElementGuid>0a210f81-2192-4299-88c8-3e1f369fca9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e62772b-8e5f-4af6-b75f-301d15d19c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acordionhealthifyDrug</value>
      <webElementGuid>ba24be61-6701-4717-96dc-10ef5ca42944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagaimana cara memesan obat di apotek online?</value>
      <webElementGuid>b822d5b9-9915-44cd-b12f-487a15800c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPanelsStayOpenExample&quot;)/div[@class=&quot;accordion-item border-0 rounded-4 shadow-sm&quot;]/h2[@class=&quot;accordion-header rounded-4&quot;]/button[@class=&quot;accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title&quot;]</value>
      <webElementGuid>d655948a-8e5a-46ce-a4be-fc9534740623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>36357cbe-ac0e-413b-a4f1-8cc1576b9b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionPanelsStayOpenExample']/div[5]/h2/button</value>
      <webElementGuid>5e0f136d-d20d-43d1-90ac-4b88628536d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah konsultasi dokter online aman?'])[1]/following::button[1]</value>
      <webElementGuid>695a9cb9-0d50-49c7-be03-bbb697a99537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara berkonsultasi dengan dokter ?'])[1]/following::button[2]</value>
      <webElementGuid>211712a1-15fb-44dc-a8f1-33b2198466e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Bergabung Bersama Kami!'])[1]/preceding::button[1]</value>
      <webElementGuid>765a2520-46e5-460a-8fc6-d6e5d471a3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perusahaan'])[1]/preceding::button[1]</value>
      <webElementGuid>4aabeffd-367c-458b-93e2-1e6e86c91854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagaimana cara memesan obat di apotek online?']/parent::*</value>
      <webElementGuid>851139a1-c3de-4e03-ba1f-ab71590a62c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/h2/button</value>
      <webElementGuid>3c5c2ce8-19e9-4d33-977c-ad078f6ff5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Bagaimana cara memesan obat di apotek online?' or . = 'Bagaimana cara memesan obat di apotek online?')]</value>
      <webElementGuid>108b5452-d564-4d4e-a1df-6f405204bfbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
