<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bagaimana cara saya mendaftar di Healthify</name>
   <tag></tag>
   <elementGuidId>5479cf88-9e9c-4b51-b309-e4fad81665dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>261a33cd-4eef-4216-8e58-f73f4043f105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title</value>
      <webElementGuid>939db2ad-ec2c-49ec-ba7f-33bd0db9d60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b699cd4c-135d-4c06-b7cf-f7c10c5af78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>071aaa7f-a5a0-48c1-bf7f-77bf855be401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#acordionhealthifyRegister</value>
      <webElementGuid>1b5b2fa2-c80b-45b0-85b7-255ed0822806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fbe55cd-3fe3-4718-bd1f-0cdd8fb02190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acordionhealthifyRegister</value>
      <webElementGuid>2d6068b2-e916-41cf-bc33-db74fa917400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagaimana cara saya mendaftar di Healthify ?</value>
      <webElementGuid>8d70bb8b-5e4d-45a7-8d35-619d666826a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPanelsStayOpenExample&quot;)/div[@class=&quot;accordion-item border-0 rounded-4 shadow-sm&quot;]/h2[@class=&quot;accordion-header rounded-4&quot;]/button[@class=&quot;accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title&quot;]</value>
      <webElementGuid>555da69b-9978-44cf-860b-498c953dc480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>39fc2493-940d-4091-b945-ca17b0833653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionPanelsStayOpenExample']/div[2]/h2/button</value>
      <webElementGuid>b9c2113a-8fef-487b-bd84-fd03f9d4e314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa itu Healthify ?'])[1]/following::button[1]</value>
      <webElementGuid>aadbf2cb-ed07-4454-b0c4-4f672414bc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequently Asked Question'])[1]/following::button[2]</value>
      <webElementGuid>e5325740-20b3-435b-9ce5-5bdbf0921354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara berkonsultasi dengan dokter ?'])[1]/preceding::button[1]</value>
      <webElementGuid>5c244c9f-5560-4205-afe2-166337b98dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah konsultasi dokter online aman?'])[1]/preceding::button[2]</value>
      <webElementGuid>93b6b5e6-17b4-44c1-8923-3478d48bae98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagaimana cara saya mendaftar di Healthify ?']/parent::*</value>
      <webElementGuid>03b3dab6-9c8e-4e9b-8695-41ed79698462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2/button</value>
      <webElementGuid>c6481e1f-3dc2-47cb-a3af-4863e087c9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Bagaimana cara saya mendaftar di Healthify ?' or . = 'Bagaimana cara saya mendaftar di Healthify ?')]</value>
      <webElementGuid>71a5659b-d0f6-4aef-b03f-c8abefb0f89b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
