<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apakah konsultasi dokter online aman</name>
   <tag></tag>
   <elementGuidId>cb5d83a6-7569-45c2-856d-047569f14c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>458c5f4a-dfdb-4ea0-bc3b-09b78824f1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title</value>
      <webElementGuid>ddd8960d-8f1e-426f-8b03-768075015a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e02bfdfb-cb59-4d8b-8210-d376df2d6bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>949d1778-1bea-488d-b28a-a6fd1e8cb6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#acordionhealthifyDoctor</value>
      <webElementGuid>2b0acb7f-8c01-4be6-a792-fc13080ce9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6fe723f-3038-4468-bf56-624b48a0bc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acordionhealthifyDoctor</value>
      <webElementGuid>8519fae5-9c4a-4292-a123-138eaf1bd88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah konsultasi dokter online aman?</value>
      <webElementGuid>9466d8f2-8000-447d-9212-fb89d78eef8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPanelsStayOpenExample&quot;)/div[@class=&quot;accordion-item border-0 rounded-4 shadow-sm&quot;]/h2[@class=&quot;accordion-header rounded-4&quot;]/button[@class=&quot;accordion-button bg-white rounded-4 text-primary fw-bold shadow-none title&quot;]</value>
      <webElementGuid>21d4a1dd-4a59-4d1b-a00d-88a6cc4b2555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>647b839f-a891-4fe8-9699-98e89543ff97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionPanelsStayOpenExample']/div[4]/h2/button</value>
      <webElementGuid>da4f27e9-1db4-431f-a5c6-690a74b60f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara berkonsultasi dengan dokter ?'])[1]/following::button[1]</value>
      <webElementGuid>e4633e06-be1c-4523-8967-95336a587787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara saya mendaftar di Healthify ?'])[1]/following::button[2]</value>
      <webElementGuid>dfab189e-ed5d-4de7-8e05-e773879e0aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara memesan obat di apotek online?'])[1]/preceding::button[1]</value>
      <webElementGuid>5dd072c5-fd3f-492e-90cb-9af0e3cef5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Bergabung Bersama Kami!'])[1]/preceding::button[2]</value>
      <webElementGuid>767c107d-fa97-423f-a6b4-10ed63ce8406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah konsultasi dokter online aman?']/parent::*</value>
      <webElementGuid>22b549cf-de2e-42bd-8974-9d4f7038dc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h2/button</value>
      <webElementGuid>8fce5cf9-21f8-41dd-8723-2b6725ce006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apakah konsultasi dokter online aman?' or . = 'Apakah konsultasi dokter online aman?')]</value>
      <webElementGuid>43369c17-058a-4d30-ab88-ca95eb9b369a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
