<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Wujudkan Kesehatanmu Untuk Hidup Bahagia Kini Dan Nanti_img-play</name>
   <tag></tag>
   <elementGuidId>28624bfb-4281-46ac-8d32-5e7a87707d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='mainHero']/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-play</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70c9cb22-e4fb-4d73-85ff-ec8b101c92b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Group-d5da103d.svg</value>
      <webElementGuid>7563e033-ad9f-4228-ab16-dafaddb7137c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>15f43c93-30c7-46a3-a346-d7c804e8ff5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>60f9208e-1bd4-41d3-82cd-90c3e842c72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-play</value>
      <webElementGuid>55e2d208-a6bc-4e1b-b050-d58d623be53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHero&quot;)/div[@class=&quot;d-flex flex-column gap-2 justify-content-center&quot;]/a[1]/img[@class=&quot;img-play&quot;]</value>
      <webElementGuid>19bc56b1-1713-44ac-8e0f-1cee55944729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='mainHero']/div[2]/a/img</value>
      <webElementGuid>0faa930e-2cab-4634-8f2b-46de8091aa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>cbc92727-4420-4a29-b0f4-9a0e165d4f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Group-d5da103d.svg']</value>
      <webElementGuid>5ba61978-c1b0-4d65-91ec-7a6b823b8b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
