<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tambah Produk_mt-2 img-fluid p-4 rounde_ad7aa7</name>
   <tag></tag>
   <elementGuidId>c7cd55df-2c6b-4b01-a74a-b6cbe79a023f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-2.img-fluid.p-4.rounded.border-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fa5b2165-cb2e-4230-9db5-1f773b17d1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/AddPhoto-03d98a02.svg</value>
      <webElementGuid>7ef8aa13-47c8-4cd7-9755-4bfd7eb558a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Placeholder</value>
      <webElementGuid>11cb9c2c-c57d-407a-9f21-3f98f72dcabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 img-fluid p-4 rounded border-primary</value>
      <webElementGuid>22d199fe-5796-4af0-aae6-6979ed1bb10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content rounded-4 border-0&quot;]/div[@class=&quot;modal-body px-5&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-12 text-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100&quot;]/img[@class=&quot;mt-2 img-fluid p-4 rounded border-primary&quot;]</value>
      <webElementGuid>6cede1cf-6c0d-456b-b97b-d5976c873126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>ea23cfd4-e8c0-45df-b62d-1675001d2926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Placeholder']</value>
      <webElementGuid>1faa5608-8934-4124-af02-391db1726461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/img</value>
      <webElementGuid>eb3562f8-3c86-4360-aead-939e402c22db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/AddPhoto-03d98a02.svg' and @alt = 'Placeholder']</value>
      <webElementGuid>b13a37aa-0f82-474d-9ac4-174d90a333e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
