<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merk_merk</name>
   <tag></tag>
   <elementGuidId>e78feccf-ac26-48e9-a54f-c50d9e2d4db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#merk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='merk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66003bd9-d4ee-4869-9dee-f342631e1b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84ae3b53-4bfc-468a-aab3-4b47c5a15e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>67a61d7c-e984-41ff-99bb-083cf437da5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merk</value>
      <webElementGuid>cae2cecb-ca4c-43d2-84a3-c19df2a9976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merk</value>
      <webElementGuid>aa950ebc-9337-4ad2-ae14-02ac0e63263a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merk&quot;)</value>
      <webElementGuid>477f5792-9a2f-4f4b-ab56-2c2443cafeec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='merk']</value>
      <webElementGuid>7954eda5-f9cf-4fff-9369-9a84e8abe336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[3]/div/input</value>
      <webElementGuid>6eae8519-6ce4-4acf-9ae1-36354a9649e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>96ff8b2d-3b56-42aa-8d40-448274ea31e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'merk' and @name = 'merk']</value>
      <webElementGuid>912db596-0546-48f2-9bcb-cb0d0419473f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
