<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Automated</name>
   <tag></tag>
   <elementGuidId>301ae33c-fd1e-4889-9106-d8102383977f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>126b1b50-0877-46af-8a80-7bae0644775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>068bb4db-95e5-4472-9445-bf98ad8e2caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1b7a73f5-d4b9-4b00-873b-34057a88533c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>19220147-38d4-4fe6-981f-5256747ff910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>details</value>
      <webElementGuid>9993146a-6e54-4d7c-84a2-795d6bc52bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automated</value>
      <webElementGuid>ed89abac-b7be-4304-8e9a-fbff3e3e852d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details&quot;)</value>
      <webElementGuid>29cb547e-aa87-4d7d-b4c6-c0bb1de9ada8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='details']</value>
      <webElementGuid>96e237d5-ca51-4b55-a68d-25aad37ffc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/form/div[8]/div/textarea</value>
      <webElementGuid>3cc9f7ae-a35b-45a7-a972-7aa02f5b04d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::textarea[1]</value>
      <webElementGuid>1cc2321d-2559-42a0-a4cd-d38749341407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga'])[2]/following::textarea[1]</value>
      <webElementGuid>f0e8d6ba-7e6d-4369-a08e-7a6aba98bb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d3f42355-709a-4417-81f6-13b01ff42be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Produk'])[1]/preceding::textarea[1]</value>
      <webElementGuid>72edfe8d-d3cd-4d3c-87b2-2c28c00abe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automated']/parent::*</value>
      <webElementGuid>2a956bbd-89b2-465b-82e0-a972b5b439bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ec3161b4-065f-4243-878d-75c9025532cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'details' and @name = 'details' and (text() = 'Automated' or . = 'Automated')]</value>
      <webElementGuid>8d1fb540-f020-4c4b-be4f-022fb1c348ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
