<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Logout</name>
   <tag></tag>
   <elementGuidId>e3d540be-2faa-4cb0-9ef8-540e0241ca82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>btn.logoutBtn.mt-3.text-primary.d-flex.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/aside/btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>b69dfb19-3004-4942-9fb1-a505501a3f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoutBtn mt-3 text-primary d-flex btn</value>
      <webElementGuid>31595de9-cf3a-4321-98f7-548318d1f574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>481ce6da-998e-4cfa-ae21-60e068ba3782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;d-none d-md-flex&quot;]/aside[@class=&quot;sidebar&quot;]/btn[@class=&quot;logoutBtn mt-3 text-primary d-flex btn&quot;]</value>
      <webElementGuid>c2cef472-e172-459d-9db3-8d6f127c46a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/aside/btn</value>
      <webElementGuid>58639489-e44b-455e-9326-69b290474710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokter'])[1]/following::btn[1]</value>
      <webElementGuid>7f449c46-8949-47a1-9527-6b3b65cc0104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pasien'])[1]/following::btn[1]</value>
      <webElementGuid>6bccf584-59ad-4bcd-9e4b-a05ac0fc6989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::btn[1]</value>
      <webElementGuid>7d00ab03-6615-4aed-ba09-fdfa69c5d45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pasien'])[1]/preceding::btn[1]</value>
      <webElementGuid>64734baf-bfb3-482c-8b5b-cb7f533798ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//btn</value>
      <webElementGuid>6c49ffb1-6cce-4919-b090-027e27a34017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//btn[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>2edb5c66-f7c0-4088-87e4-425e75701648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
