<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transaksi Pembelian Obat_searchMedicine</name>
   <tag></tag>
   <elementGuidId>52e3e751-6d9c-4bab-9a2a-53e5c400bd8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchMedicine&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchMedicine']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b10c582d-4fd1-49a4-96da-63e1ae8ac702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62a1a04b-6e29-4a3b-b452-69c51c26cf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-5 ps-5 border-0 bg-white py-2</value>
      <webElementGuid>a335b562-4d79-4879-8939-cdd987f4b042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchMedicine</value>
      <webElementGuid>fee9c82c-ed16-474b-ab0c-9d881d0500a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari ID Transaksi</value>
      <webElementGuid>b2b76b2b-f9f9-4fb9-a876-9f036fb9b6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;mx-4 d-flex flex-column gap-4&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;table-responsive rounded-4 p-4 border&quot;]/div[@class=&quot;d-flex flex-column flex-md-row justify-content-md-between align-items-md-center mb-4&quot;]/div[@class=&quot;position-relative mt-3 mt-md-0&quot;]/input[@class=&quot;rounded-5 ps-5 border-0 bg-white py-2&quot;]</value>
      <webElementGuid>f7174da9-d5d0-42be-af21-da6f78d7f504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchMedicine']</value>
      <webElementGuid>d8c54dae-ca22-4584-baef-aeefb051a426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div[2]/div/div/input</value>
      <webElementGuid>f7fcc15e-079c-4312-a8e2-9394c32d12db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>669458ed-144f-497e-ac4e-e15637c86f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchMedicine' and @placeholder = 'Cari ID Transaksi']</value>
      <webElementGuid>96a6d14d-036d-402d-b471-7c8b6eccaeff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
