<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pengalaman_experience</name>
   <tag></tag>
   <elementGuidId>564721d8-012a-4c9b-8067-ce08481e2fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;experience&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='experience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e17bc20c-5812-4484-ba05-decb04e02d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f910586e-b357-444b-98c4-11398d388b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3 col-12 col-lg input-styles </value>
      <webElementGuid>3fa87b4d-2fb0-4a2a-b79e-0c86de48b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>experience</value>
      <webElementGuid>d3612554-fec2-45bb-8ec3-408c943feca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tahun Pengalaman Praktik</value>
      <webElementGuid>cfe9b4cb-0961-46c0-ac5b-43364c7eddda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5 Tahun</value>
      <webElementGuid>4647820c-87c5-4bbd-be67-bc39500b0ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;h-100 d-flex flex-row&quot;]/div[@class=&quot;drawer-content&quot;]/section[@class=&quot;container-fluid&quot;]/div[@class=&quot;my-3 d-flex flex-column flex-lg-row align-items-center align-items-lg-start justify-content-lg-center gap-3&quot;]/div[@class=&quot;d-grid list-input pt-1&quot;]/form[@class=&quot;d-grid gap-2&quot;]/div[@class=&quot;row align-items-md-center gap-2&quot;]/input[@class=&quot;form-control p-3 col-12 col-lg input-styles&quot;]</value>
      <webElementGuid>c3e576fd-c2dc-418b-b712-f4f801b8031e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='experience']</value>
      <webElementGuid>1570d51f-5457-411f-9836-768ff2c3ca75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/section/div/div[2]/form/div[11]/input</value>
      <webElementGuid>2e0ad5fd-f1d6-4983-b512-706668b29972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>55f4bd07-debc-4dd1-a702-89e1e88d01dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'experience' and @placeholder = 'Tahun Pengalaman Praktik']</value>
      <webElementGuid>107e5140-0cb2-4b00-bed7-13709f1c7145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
