<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Link</name>
   <tag></tag>
   <elementGuidId>c05d406c-e6ca-4ffb-aefc-eb081df558c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.p-0.ms-1.text-primary.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b64cc116-65da-4edb-aa6a-22107d1fdddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c010c33-ee3c-4e52-8d8b-d3cf8f7beac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn p-0 ms-1 text-primary fw-semibold</value>
      <webElementGuid>4021e795-53ce-4cc6-9314-4aa614935a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>02ef8682-e6b5-4038-8bed-9b8b3e9cb3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalTransactionMedicine&quot;)/section[@class=&quot;transaction-modal bg-light&quot;]/div[@class=&quot;p-3 d-flex flex-column gap-3&quot;]/section[1]/div[@class=&quot;row text-capitalize&quot;]/div[@class=&quot;col-6 d-flex flex-column gap-2&quot;]/div[@class=&quot;d-inline-flex&quot;]/button[@class=&quot;btn p-0 ms-1 text-primary fw-semibold&quot;]</value>
      <webElementGuid>d1063e7c-a056-48ec-97c0-8dbf15d3e465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>bdbe97bb-c157-4221-886c-421123dcaa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalTransactionMedicine']/section/div[2]/section/div/div[2]/div/button</value>
      <webElementGuid>06b6dae8-8a20-4a76-9cef-360ed55e4a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>cd49f6bb-e052-4df6-8fba-dd2128246d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi Obat'])[1]/following::button[1]</value>
      <webElementGuid>57365e84-548a-4fb0-9ef1-8917e3e10f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pembelian'])[1]/preceding::button[1]</value>
      <webElementGuid>1533ab4d-9d86-48e8-837b-a412f01a16f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Obat'])[1]/preceding::button[1]</value>
      <webElementGuid>7be4c7f6-8e78-4820-8ddc-44fd5bea142c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>7c821f28-899d-46ce-afb1-bfcf1d2fc193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Link' or . = 'Link')]</value>
      <webElementGuid>7cdf40b1-e303-4b83-8e0e-1264f2dcf08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
